amagi/amagi/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'amagi.views.home', name='home'),
    # url(r'^amagi/', include('amagi.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    # Django registration urls
    (r'^accounts/', include('registration.backends.default.urls')),

    # UserFile ursl
    url(r'^accounts/profile/', include('dropboxapp.urls')),

    # Dropbox registration
    url(r'^register_dropbox', 'dropboxapp.views.register', name='register'),

    # Sync Dropbox File
    url(r'^sync_dropbox', 'dropboxapp.views.sync', name='sync'),

    (r'^about/$', TemplateView.as_view(template_name="about.html")),

    (r'^contact/$', TemplateView.as_view(template_name="contact.html")),

    (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT})
)

amagi/dropboxapp/urls.py
from django.conf.urls import patterns, url

from dropboxapp import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index')
)

amagi/dropboxapp/models.py
from django.db import models
from django.contrib.auth.models import User

class DropBoxUser(models.Model):
    user = models.ForeignKey(User)
    auth_code = models.CharField(max_length=255)
    dropbox_user_id = models.IntegerField(blank=True, null=True)
    dropbox_access_token = models.CharField(max_length=255, blank=True, null=True)
    added_date = models.DateTimeField('date added')

class UserFile(models.Model):
    user = models.ForeignKey(User)
    dropbox_user = models.ForeignKey(DropBoxUser)
    name = models.CharField(max_length=255)
    file = models.FileField(upload_to='user_files')
    uploaded_date = models.DateTimeField('date uploaded')

amagi/amagi/views.py
from django.http import HttpResponse
from django.template import RequestContext, loader
from dropboxapp.models import UserFile

def home(request):
    template = loader.get_template('index.html')
    context = RequestContext(request, {
    })
    return HttpResponse(template.render(context))

amagi/dropboxapp/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext, loader
from dropboxapp.models import UserFile, DropBoxUser
from dropbox.client import DropboxOAuth2FlowNoRedirect, DropboxClient
from django.conf import settings
from django import forms
import datetime
from django.core.files.base import ContentFile
import thread

class RegisterForm(forms.Form):
    auth_code = forms.CharField(max_length=255)

class SyncForm(forms.Form):
    file_name = forms.CharField(max_length=255)

def index(request):
    current_user = request.user
    user_files = UserFile.objects.filter(user__id=current_user.id)
    folder_metadata = ''
    dropbox_files = None

    try:
        dropbox_user = DropBoxUser.objects.get(user__id=current_user.id)
        access_token = dropbox_user.dropbox_access_token
        client = DropboxClient(access_token)
        folder_metadata = client.metadata('/')
        dropbox_files = [content["path"] for content in folder_metadata["contents"]]
    except DropBoxUser.DoesNotExist:
        dropbox_user = ''

    template = loader.get_template('dropbox/index.html')
    form = SyncForm()

    context = RequestContext(request, {
        'files': user_files,
        'user': current_user,
        'dropbox_user': dropbox_user,
        'metadata': folder_metadata,
        'dropbox_files': dropbox_files,
        'form': form,
        'MEDIA_ROOT': settings.MEDIA_ROOT,
    })
    return HttpResponse(template.render(context))


def register(request):
    if request.method == 'POST':
        current_user = request.user
        form = RegisterForm(request.POST)
        if form.is_valid():
            try:
                DropBoxUser.objects.get(user=current_user)
            except DropBoxUser.DoesNotExist:
                auth_code = form.cleaned_data['auth_code']
                added_date = datetime.datetime.now()
                app_key = settings.APP_KEY
                app_secret = settings.APP_SECRET
                flow = DropboxOAuth2FlowNoRedirect(app_key, app_secret)
                flow.start()
                access_token, user_id = flow.finish(auth_code)
                DropBoxUser.objects.create(user=current_user,
                                           auth_code=auth_code,
                                           added_date=added_date,
                                           dropbox_user_id=user_id,
                                           dropbox_access_token=access_token,
                                           )
            template = loader.get_template('dropbox/index.html')
            context = RequestContext(request, {
                'user': current_user,
                'form': form,
                'MEDIA_ROOT': settings.MEDIA_ROOT,
            })
            return HttpResponse(template.render(context))
    else:
        current_user = request.user
        # Dropbox api flow
        app_key = settings.APP_KEY
        app_secret = settings.APP_SECRET
        flow = DropboxOAuth2FlowNoRedirect(app_key, app_secret)
        authorize_url = flow.start()
        template = loader.get_template('dropbox/register.html')
        form = RegisterForm()
        context = RequestContext(request, {
            'user': current_user,
            'authorize_url': authorize_url,
            'form': form,
            'flow': flow,
        })
    return HttpResponse(template.render(context))

def do_sync_bg(request):
    current_user = request.user
    form = SyncForm(request.POST)
    dropbox_user = None
    if form.is_valid():
        try:
            dropbox_user = DropBoxUser.objects.get(user=current_user)
        except DropBoxUser.DoesNotExist:
            pass # Handle if dropbox user was never created to begin with
        file_name = request.POST['file_name']
        uploaded_date = datetime.datetime.now()
        client = DropboxClient(dropbox_user.dropbox_access_token)
        f = client.get_file(file_name)
        cf = ContentFile(f.read())
        user_file = UserFile.objects.create(user=current_user,
                                dropbox_user=dropbox_user,
                                name=file_name,
                                uploaded_date=uploaded_date)
        user_file.file.save(file_name, cf)


def sync(request):
    if request.method == 'POST':
        thread.start_new_thread(do_sync_bg, (request,))
        current_user = request.user
        form = SyncForm(request.POST)
    else:
        current_user = request.user
        form = SyncForm()

    context = RequestContext(request, {
            'user': current_user,
            'form': form,
            'MEDIA_ROOT': settings.MEDIA_ROOT,
        })
    template = loader.get_template('dropbox/index.html')
    return HttpResponse(template.render(context))

amagi/amagi/templates/about.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
    <div class="jumbotron">
        DropBox App demo to sync files from your dropbox account and play on our servers.
    </div>
{% endblock %}

amagi/amagi/templates/base.html
{% load i18n %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>
    <link rel="/Users/sachin/amagi/amagi/amagi/static/stylesheet" href="style.css" />
    <title>{% block title %}DropBox App{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">
    <!-- Custom styles for this template -->
    <link href="jumbo.css" rel="/Users/sachin/amagi/amagi/amagi/static/stylesheet">
</head>

<body>
    <script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>

    <!-- BOOTSTRAP -->

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">DropBoxApp</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/">Home</a></li>
            <li><a href="/about">About</a></li>
            <li><a href="/contact">Contact</a></li>
          </ul>

            {% if user.is_authenticated %}
                <div class="toptext" align="right" style="color:#e1e1e1;margin-top:8px;">
                    {% trans "Welcome " %} {{ user.username|title }} &nbsp;&nbsp;

                    <a class="btn btn-primary" href="{% url 'auth_logout' %}">{% trans "Log out" %}</a> &nbsp;
                    <a class="btn btn-primary" href="{% url 'auth_password_change' %}">{% trans "Change password" %}</a>
                </div>
            {% else %}
                <form class="navbar-form navbar-right" method="post" action="/accounts/login/">
                    {% csrf_token %}
                    <div class="form-group">
                      <input id="id_username" name="username" type="text" placeholder="Username" class="form-control">
                    </div>
                    <div class="form-group">
                      <input id="id_password" name="password" type="password" placeholder="Password" class="form-control">
                    </div>
                    <button type="submit" class="btn btn-success">Sign in</button>
                    <input type="hidden" name="next" value="{{ next }}" />
                  </form>
            {% endif %}
        </div><!--/.navbar-collapse -->
      </div>
    </div>

    
    <!-- BOOTSTRAP END -->
 

    <div id="header">
        {% block header %}
	<a href="/">{% trans "Home" %}</a> |

	<hr />
        {% endblock %}
    </div>

    <div id="content">
        {% block content %}{% endblock %}
    </div>

    <div id="footer">
        {% block footer %}
        <hr />
        {% endblock %}
    </div>
</body>

</html>

amagi/amagi/templates/contact.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
    <div class="jumbotron">
        For any queries contact: <br/>
        Sachin Prabhu <br/>
        Email : galacticsurfer@gmail.com <br/>
        Phone : +91 9986358053
    </div>
{% endblock %}

amagi/amagi/templates/dropbox/index.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
    <div class="jumbotron">
        Welcome {{ user }} you currently have {{ files|length }} Files. <br/>

        {% if files|length > 0 %}

        {% endif %}
        <table class="table table-bordered">
            <th>Your Files on the App</th>
            {% for file in files %}
                <tr>
                    <td>
                        <a href = "{{MEDIA_ROOT}}{{file.name}}">{{file.name}}</a> &nbsp;&nbsp;
                        {% if '.mp4' in file.name %}
                            <video width="320" height="240" controls>
                                <source src="/media{{file.name}}" type="video/mp4">
                                Your browser does not support the video tag.
                            </video>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </table>

        <form action="/sync_dropbox/" method="post">{% csrf_token %}
            <p><label for="id_file_name">File name:</label> <input id="id_file_name" class="form-control" maxlength="255" name="file_name" type="text" placeholder="Complete file path from your dropbox account"></p>
            <input class="btn btn-success" type="submit" value="Sync">
        </form>

        <br/>

        {% if dropbox_user != '' %}
            Would you like to sync some files ? <br/>
            Your Dropbox Files : <br/>
            <table class="table table-bordered">
                <th>Your Files on your DropBox Account</th>
                {% for file in dropbox_files %}
                    <tr>
                        <td>
                            {{ file }}
                        </td>
                    </tr>
                {% endfor %}
            </table>
        {% else %}
            I see you have not registered a dropbox account with us , care to sync it with our app ? :) <br/>
            <a href="https://www.dropbox.com/home">Click here</a> to register a dropbox account OR <br/>
            <a href="/register_dropbox">Click here</a> to register with our api. <br/>
        {% endif %}
    </div>
{% endblock %}

amagi/amagi/templates/dropbox/register.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
    <div class="jumbotron">
        Welcome {{ user }} <br/><br/>

        Steps to register with us.<br/>
        1. First <a class="btn btn-primary" href="{{authorize_url}}" target="_blank"> Click Here </a> <br/>
        2. Click "Allow" (you might have to log in first)<br/>
        3. Copy the authorization code.<br/>
        4. Enter the authorization code below<br/>

        <form action="/register_dropbox/" method="post">
            {% csrf_token %}
            <p><label for="id_auth_code">Auth code:</label> <input id="id_auth_code" class="form-control" maxlength="255" name="auth_code" type="text"></p>
            <input class="btn btn-success" type="submit" value="Submit">
        </form>
    </div>

{% endblock %}

amagi/amagi/templates/index.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
    <div class="jumbotron">
        {% if user.is_authenticated %}
            Hello {{ user }} , You can sync your dropbox account if you haven't already <br/>
            You can do it <a class="btn btn-primary" href="/accounts/profile/">Here</a>
        {% else %}
            Welcome to the dropbox web app Please log in . <br/>
            If you dont have an account, <a class="btn btn-primary" href="/accounts/register">Sign up</a> !
        {% endif %}
    </div>
{% endblock %}